//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheKing {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TheKing.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string bank_balance_request {
            get {
                return ResourceManager.GetString("bank_balance_request", resourceCulture);
            }
        }
        
        internal static string bank_balance_response {
            get {
                return ResourceManager.GetString("bank_balance_response", resourceCulture);
            }
        }
        
        internal static string bank_welcome {
            get {
                return ResourceManager.GetString("bank_welcome", resourceCulture);
            }
        }
        
        internal static string go_back_to_start {
            get {
                return ResourceManager.GetString("go_back_to_start", resourceCulture);
            }
        }
        
        internal static string go_to_bank {
            get {
                return ResourceManager.GetString("go_to_bank", resourceCulture);
            }
        }
        
        internal static string go_to_map {
            get {
                return ResourceManager.GetString("go_to_map", resourceCulture);
            }
        }
        
        internal static string hello_message {
            get {
                return ResourceManager.GetString("hello_message", resourceCulture);
            }
        }
        
        internal static string here_is {
            get {
                return ResourceManager.GetString("here_is", resourceCulture);
            }
        }
        
        internal static string income_request {
            get {
                return ResourceManager.GetString("income_request", resourceCulture);
            }
        }
        
        internal static string income_response {
            get {
                return ResourceManager.GetString("income_response", resourceCulture);
            }
        }
        
        internal static string look_at {
            get {
                return ResourceManager.GetString("look_at", resourceCulture);
            }
        }
        
        internal static string next_day {
            get {
                return ResourceManager.GetString("next_day", resourceCulture);
            }
        }
        
        internal static string outcome_request {
            get {
                return ResourceManager.GetString("outcome_request", resourceCulture);
            }
        }
        
        internal static string outcome_response {
            get {
                return ResourceManager.GetString("outcome_response", resourceCulture);
            }
        }
        
        internal static string root_message {
            get {
                return ResourceManager.GetString("root_message", resourceCulture);
            }
        }
        
        internal static string taxes_name {
            get {
                return ResourceManager.GetString("taxes_name", resourceCulture);
            }
        }
        
        internal static string time_report {
            get {
                return ResourceManager.GetString("time_report", resourceCulture);
            }
        }
        
        internal static string army_welcome {
            get {
                return ResourceManager.GetString("army_welcome", resourceCulture);
            }
        }
        
        internal static string army_recruit_request {
            get {
                return ResourceManager.GetString("army_recruit_request", resourceCulture);
            }
        }
        
        internal static string army_recruit_request_2 {
            get {
                return ResourceManager.GetString("army_recruit_request_2", resourceCulture);
            }
        }
        
        internal static string army_recruit_response {
            get {
                return ResourceManager.GetString("army_recruit_response", resourceCulture);
            }
        }
        
        internal static string go_to_army {
            get {
                return ResourceManager.GetString("go_to_army", resourceCulture);
            }
        }
        
        internal static string army_name {
            get {
                return ResourceManager.GetString("army_name", resourceCulture);
            }
        }
        
        internal static string game_over_money {
            get {
                return ResourceManager.GetString("game_over_money", resourceCulture);
            }
        }
        
        internal static string here_empty {
            get {
                return ResourceManager.GetString("here_empty", resourceCulture);
            }
        }
        
        internal static string here_live {
            get {
                return ResourceManager.GetString("here_live", resourceCulture);
            }
        }
        
        internal static string race_Goblin {
            get {
                return ResourceManager.GetString("race_Goblin", resourceCulture);
            }
        }
        
        internal static string race_Human {
            get {
                return ResourceManager.GetString("race_Human", resourceCulture);
            }
        }
        
        internal static string army_conquest_request {
            get {
                return ResourceManager.GetString("army_conquest_request", resourceCulture);
            }
        }
        
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        internal static string conquest_failed {
            get {
                return ResourceManager.GetString("conquest_failed", resourceCulture);
            }
        }
        
        internal static string conquest_success {
            get {
                return ResourceManager.GetString("conquest_success", resourceCulture);
            }
        }
        
        internal static string army_conquest_request_2 {
            get {
                return ResourceManager.GetString("army_conquest_request_2", resourceCulture);
            }
        }
        
        internal static string army_conquest_response {
            get {
                return ResourceManager.GetString("army_conquest_response", resourceCulture);
            }
        }
        
        internal static string here_unknown {
            get {
                return ResourceManager.GetString("here_unknown", resourceCulture);
            }
        }
        
        internal static string game_over_locations {
            get {
                return ResourceManager.GetString("game_over_locations", resourceCulture);
            }
        }
        
        internal static string country_Dwarf_0 {
            get {
                return ResourceManager.GetString("country_Dwarf_0", resourceCulture);
            }
        }
        
        internal static string country_Dwarf_1 {
            get {
                return ResourceManager.GetString("country_Dwarf_1", resourceCulture);
            }
        }
        
        internal static string country_Dwarf_2 {
            get {
                return ResourceManager.GetString("country_Dwarf_2", resourceCulture);
            }
        }
        
        internal static string country_Elf_0 {
            get {
                return ResourceManager.GetString("country_Elf_0", resourceCulture);
            }
        }
        
        internal static string country_Elf_1 {
            get {
                return ResourceManager.GetString("country_Elf_1", resourceCulture);
            }
        }
        
        internal static string country_Elf_2 {
            get {
                return ResourceManager.GetString("country_Elf_2", resourceCulture);
            }
        }
        
        internal static string country_Goblin_0 {
            get {
                return ResourceManager.GetString("country_Goblin_0", resourceCulture);
            }
        }
        
        internal static string country_Goblin_1 {
            get {
                return ResourceManager.GetString("country_Goblin_1", resourceCulture);
            }
        }
        
        internal static string country_Goblin_2 {
            get {
                return ResourceManager.GetString("country_Goblin_2", resourceCulture);
            }
        }
        
        internal static string country_Halfling_0 {
            get {
                return ResourceManager.GetString("country_Halfling_0", resourceCulture);
            }
        }
        
        internal static string country_Halfling_1 {
            get {
                return ResourceManager.GetString("country_Halfling_1", resourceCulture);
            }
        }
        
        internal static string country_Halfling_2 {
            get {
                return ResourceManager.GetString("country_Halfling_2", resourceCulture);
            }
        }
        
        internal static string country_Human_0 {
            get {
                return ResourceManager.GetString("country_Human_0", resourceCulture);
            }
        }
        
        internal static string country_Human_1 {
            get {
                return ResourceManager.GetString("country_Human_1", resourceCulture);
            }
        }
        
        internal static string country_Human_2 {
            get {
                return ResourceManager.GetString("country_Human_2", resourceCulture);
            }
        }
        
        internal static string country_Orc_0 {
            get {
                return ResourceManager.GetString("country_Orc_0", resourceCulture);
            }
        }
        
        internal static string country_Orc_1 {
            get {
                return ResourceManager.GetString("country_Orc_1", resourceCulture);
            }
        }
        
        internal static string country_Orc_2 {
            get {
                return ResourceManager.GetString("country_Orc_2", resourceCulture);
            }
        }
        
        internal static string loc_names_Barrens {
            get {
                return ResourceManager.GetString("loc_names_Barrens", resourceCulture);
            }
        }
        
        internal static string loc_names_Lands {
            get {
                return ResourceManager.GetString("loc_names_Lands", resourceCulture);
            }
        }
        
        internal static string loc_names_Mountains {
            get {
                return ResourceManager.GetString("loc_names_Mountains", resourceCulture);
            }
        }
        
        internal static string loc_names_Sea {
            get {
                return ResourceManager.GetString("loc_names_Sea", resourceCulture);
            }
        }
        
        internal static string loc_names_Woods {
            get {
                return ResourceManager.GetString("loc_names_Woods", resourceCulture);
            }
        }
        
        internal static string loc_prefixes_Barrens {
            get {
                return ResourceManager.GetString("loc_prefixes_Barrens", resourceCulture);
            }
        }
        
        internal static string loc_prefixes_Lands {
            get {
                return ResourceManager.GetString("loc_prefixes_Lands", resourceCulture);
            }
        }
        
        internal static string loc_prefixes_Mountains {
            get {
                return ResourceManager.GetString("loc_prefixes_Mountains", resourceCulture);
            }
        }
        
        internal static string loc_prefixes_Sea {
            get {
                return ResourceManager.GetString("loc_prefixes_Sea", resourceCulture);
            }
        }
        
        internal static string loc_prefixes_Woods {
            get {
                return ResourceManager.GetString("loc_prefixes_Woods", resourceCulture);
            }
        }
        
        internal static string race_Dwarf {
            get {
                return ResourceManager.GetString("race_Dwarf", resourceCulture);
            }
        }
        
        internal static string race_Elf {
            get {
                return ResourceManager.GetString("race_Elf", resourceCulture);
            }
        }
        
        internal static string race_Halfling {
            get {
                return ResourceManager.GetString("race_Halfling", resourceCulture);
            }
        }
        
        internal static string race_Orc {
            get {
                return ResourceManager.GetString("race_Orc", resourceCulture);
            }
        }
        
        internal static string win_conquest {
            get {
                return ResourceManager.GetString("win_conquest", resourceCulture);
            }
        }
        
        internal static string here_lived {
            get {
                return ResourceManager.GetString("here_lived", resourceCulture);
            }
        }
        
        internal static string enemy_failed {
            get {
                return ResourceManager.GetString("enemy_failed", resourceCulture);
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string enemy_conquest_fail {
            get {
                return ResourceManager.GetString("enemy_conquest_fail", resourceCulture);
            }
        }
        
        internal static string enemy_conquest_result {
            get {
                return ResourceManager.GetString("enemy_conquest_result", resourceCulture);
            }
        }
        
        internal static string enemy_conquest_success {
            get {
                return ResourceManager.GetString("enemy_conquest_success", resourceCulture);
            }
        }
        
        internal static string race_select {
            get {
                return ResourceManager.GetString("race_select", resourceCulture);
            }
        }
        
        internal static string mode_normal {
            get {
                return ResourceManager.GetString("mode_normal", resourceCulture);
            }
        }
        
        internal static string mode_free {
            get {
                return ResourceManager.GetString("mode_free", resourceCulture);
            }
        }
        
        internal static string one_alive {
            get {
                return ResourceManager.GetString("one_alive", resourceCulture);
            }
        }
    }
}
