//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheKing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheKing.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to extend my kingdom..
        /// </summary>
        internal static string army_conquest_request {
            get {
                return ResourceManager.GetString("army_conquest_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army.
        /// </summary>
        internal static string army_name {
            get {
                return ResourceManager.GetString("army_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to recruit more soldiers..
        /// </summary>
        internal static string army_recruit_request {
            get {
                return ResourceManager.GetString("army_recruit_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - How many? ({0}/soldier, max: {1}).
        /// </summary>
        internal static string army_recruit_request_2 {
            get {
                return ResourceManager.GetString("army_recruit_request_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Roger that!.
        /// </summary>
        internal static string army_recruit_response {
            get {
                return ResourceManager.GetString("army_recruit_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Greetings, my lord!.
        /// </summary>
        internal static string army_welcome {
            get {
                return ResourceManager.GetString("army_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much gold do we have?.
        /// </summary>
        internal static string bank_balance_request {
            get {
                return ResourceManager.GetString("bank_balance_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - We have {0} gold coins, sir..
        /// </summary>
        internal static string bank_balance_response {
            get {
                return ResourceManager.GetString("bank_balance_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Greetings, my master!.
        /// </summary>
        internal static string bank_welcome {
            get {
                return ResourceManager.GetString("bank_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your treasury is empty..
        /// </summary>
        internal static string game_over_money {
            get {
                return ResourceManager.GetString("game_over_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back..
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to the throne..
        /// </summary>
        internal static string go_back_to_start {
            get {
                return ResourceManager.GetString("go_back_to_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the general..
        /// </summary>
        internal static string go_to_army {
            get {
                return ResourceManager.GetString("go_to_army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the paymaster..
        /// </summary>
        internal static string go_to_bank {
            get {
                return ResourceManager.GetString("go_to_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the map..
        /// </summary>
        internal static string go_to_map {
            get {
                return ResourceManager.GetString("go_to_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Hello, your majesty! It is first day of your regiment..
        /// </summary>
        internal static string hello_message {
            get {
                return ResourceManager.GetString("hello_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody lives here..
        /// </summary>
        internal static string here_empty {
            get {
                return ResourceManager.GetString("here_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is {0}..
        /// </summary>
        internal static string here_is {
            get {
                return ResourceManager.GetString("here_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here live: {0} ({1})..
        /// </summary>
        internal static string here_live {
            get {
                return ResourceManager.GetString("here_live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did we earn yesterday?.
        /// </summary>
        internal static string income_request {
            get {
                return ResourceManager.GetString("income_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - We earn {0} coins for:.
        /// </summary>
        internal static string income_response {
            get {
                return ResourceManager.GetString("income_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at {0}..
        /// </summary>
        internal static string look_at {
            get {
                return ResourceManager.GetString("look_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the bed..
        /// </summary>
        internal static string next_day {
            get {
                return ResourceManager.GetString("next_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did we spent yesterday?.
        /// </summary>
        internal static string outcome_request {
            get {
                return ResourceManager.GetString("outcome_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - We spent {0} coins for:.
        /// </summary>
        internal static string outcome_response {
            get {
                return ResourceManager.GetString("outcome_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goblins.
        /// </summary>
        internal static string race_Goblin {
            get {
                return ResourceManager.GetString("race_Goblin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to humans.
        /// </summary>
        internal static string race_Human {
            get {
                return ResourceManager.GetString("race_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s you again..
        /// </summary>
        internal static string root_message {
            get {
                return ResourceManager.GetString("root_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        internal static string taxes_name {
            get {
                return ResourceManager.GetString("taxes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is {0}..
        /// </summary>
        internal static string time_report {
            get {
                return ResourceManager.GetString("time_report", resourceCulture);
            }
        }
    }
}
