//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheKing {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TheKing.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string bank_balance_request {
            get {
                return ResourceManager.GetString("bank_balance_request", resourceCulture);
            }
        }
        
        internal static string bank_balance_response {
            get {
                return ResourceManager.GetString("bank_balance_response", resourceCulture);
            }
        }
        
        internal static string bank_welcome {
            get {
                return ResourceManager.GetString("bank_welcome", resourceCulture);
            }
        }
        
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        internal static string go_to_bank {
            get {
                return ResourceManager.GetString("go_to_bank", resourceCulture);
            }
        }
        
        internal static string go_to_map {
            get {
                return ResourceManager.GetString("go_to_map", resourceCulture);
            }
        }
        
        internal static string hello_message {
            get {
                return ResourceManager.GetString("hello_message", resourceCulture);
            }
        }
        
        internal static string here_is {
            get {
                return ResourceManager.GetString("here_is", resourceCulture);
            }
        }
        
        internal static string income_request {
            get {
                return ResourceManager.GetString("income_request", resourceCulture);
            }
        }
        
        internal static string income_response {
            get {
                return ResourceManager.GetString("income_response", resourceCulture);
            }
        }
        
        internal static string look_at {
            get {
                return ResourceManager.GetString("look_at", resourceCulture);
            }
        }
        
        internal static string next_day {
            get {
                return ResourceManager.GetString("next_day", resourceCulture);
            }
        }
        
        internal static string outcome_request {
            get {
                return ResourceManager.GetString("outcome_request", resourceCulture);
            }
        }
        
        internal static string outcome_response {
            get {
                return ResourceManager.GetString("outcome_response", resourceCulture);
            }
        }
        
        internal static string root_message {
            get {
                return ResourceManager.GetString("root_message", resourceCulture);
            }
        }
        
        internal static string taxes_name {
            get {
                return ResourceManager.GetString("taxes_name", resourceCulture);
            }
        }
        
        internal static string time_report {
            get {
                return ResourceManager.GetString("time_report", resourceCulture);
            }
        }
        
        internal static string army_welcome {
            get {
                return ResourceManager.GetString("army_welcome", resourceCulture);
            }
        }
        
        internal static string army_recruit_request {
            get {
                return ResourceManager.GetString("army_recruit_request", resourceCulture);
            }
        }
        
        internal static string army_recruit_request_2 {
            get {
                return ResourceManager.GetString("army_recruit_request_2", resourceCulture);
            }
        }
        
        internal static string army_recruit_response {
            get {
                return ResourceManager.GetString("army_recruit_response", resourceCulture);
            }
        }
        
        internal static string go_to_army {
            get {
                return ResourceManager.GetString("go_to_army", resourceCulture);
            }
        }
        
        internal static string army_name {
            get {
                return ResourceManager.GetString("army_name", resourceCulture);
            }
        }
        
        internal static string game_over_money {
            get {
                return ResourceManager.GetString("game_over_money", resourceCulture);
            }
        }
    }
}
